server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fcrestaurants
    username: root
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      secret: ${secret}
      expiration: 604800000
      user-generator: ${user_generator}